trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.13.2'
  inputs:
    terraformVersion: 0.13.2
    
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    backendAzureRmResourceGroupName: 'VikasRg'
    backendAzureRmStorageAccountName: 'devtestlb'
    backendAzureRmContainerName: 'terraformpipelinebackend'
    backendAzureRmKey: 'backed'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    commandOptions: '-auto-approve'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    commandOptions: '-auto-approve'
    allowTelemetryCollection: true
