# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    backendAzureRmResourceGroupName: 'VikasRg'
    backendAzureRmStorageAccountName: 'devtestlb'
    backendAzureRmContainerName: 'terraformpipelinebackend'
    backendAzureRmKey: 'backed'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'Visual Studio Enterprise (883bf586-e0da-4577-91da-2a0f42a08f64)'
    commandOptions: '-auto-approve'
    allowTelemetryCollection: true

